version: '2'
services:
  #db: (let's totes do pg in dev)
    #image: postgres
  elasticsearch:
    image: elasticsearch:1.7
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    env_file: .env
    depends_on:
      - elasticsearch
      #- db
