# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a70e7ee1931932e7011d7e101d6d257b86ab42b0e6b0b3a8e85583c8eb95d8bfbb0d1bd756852d55364c9ae7e38986c91520ee360c7414232ded10d1e495d6b

test:
  secret_key_base: 4a8979f5423bae755615c30d149cb96f5792d81677029f6ac2e7333178c759c6df542919bfb7658d0ed77d037cfd25b52b93f8295008ad19d363d6503674a326

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
